### ISSUE TITLE
Сделать так что бы gulp обрабатывал все файлы js и передавал их в build 

### ISSUE THREAD

**Issue by IvanovEV92** [axZerk/gulp-starter-kit#25]
Предистория такова что в сбоку подключил webpack для обработки js файлов 
подскажите как мне переписать конфиг таким образом что бы галп обрабатывал несколько файлов js
http://joxi.ru/Dr8dWJQho9RVVr
идея в том что у меня на сайте 3 станицы и я хочу к каждой странице подключить отдельный файл скриптов а то у меня конфликты выходят если использовать 1 файл
то есть мне нужно просто все файлы js перенести в папку build

**Comment by luxplanjay** [comment]
Для этого необходимо настроить вебпак с поддержкой многостраничных приложений https://webpack.js.org/concepts/entry-points/#multi-page-application

**Comment by IvanovEV92** [comment]
Вот пока с конфигами беда :( от слова совсем 
Возможно Вы сможете подсказать как именно правильно нужно вывать эти самые entry

ниже файл конфига скриптов (если нужно могу всю сборку предоставить)

>`const gulp = require('gulp');
const babel = require('gulp-babel');
const mode = require('gulp-mode')();
const fileinclude = require('gulp-file-include');
const paths = require('../paths');
const webpack = require('webpack');
const webpackStream = require('webpack-stream');
const uglify = require('gulp-uglify-es').default;
const scripts = () => {
  return gulp
    .src(paths.src.js)
    .pipe(fileinclude())
    .pipe(
      webpackStream({
        mode: 'development',
        output: {
          filename: 'scripts.js',
        },
        module: {
          rules: [
            {
              test: /\.m?js$/,
              exclude: /(node_modules|bower_components)/,
              use: {
                loader: 'babel-loader',
                options: {
                  presets: ['@babel/preset-env'],
                },
              },
            },
            {
              test: /\.css$/,
              use: ['style-loader', 'css-loader'],
            },
            {
              test: /\.scss$/,
              use: ['style-loader', 'css-loader', 'sass-loader'],
            },
            {
              test: /\.(gif|png|jpe?g|svg)$/i,
              use: [
                {
                  loader: 'url-loader',
                  options: {
                    name: '[path][name].[ext]',
                    limit: 8192,
                    esModule: false,
                  },
                },
                'img-loader',
              ],
            },
            {
              test: /\.hbs$/,
              use: 'handlebars-loader',
            },
            {
              test: /\.woff(2)?(\?[a-z0-9#=&.]+)?$/,
              use: [
                {
                  loader: 'url-loader',
                  options: {
                    name: '[name].[ext]',
                    outputPath: 'fonts/',
                    limit: 10000,
                    mimetype: 'application/font-woff',
                  },
                },
              ],
            },
            {
              test: /\.(ttf|eot)(\?v=\d+\.\d+\.\d+)?$/,
              use: [
                {
                  loader: 'file-loader',
                  options: {
                    name: '[name].[ext]',
                    outputPath: 'fonts/',
                  },
                },
              ],
            },
          ],
        },
      }),
    )
    .pipe(babel())
    .pipe(mode.production(uglify()))
    .pipe(gulp.dest(paths.build.js));
};

module.exports = scripts;`
