### ISSUE TITLE
gulp-starter-kit bugs

### ISSUE THREAD

**Issue by nerty777** [axZerk/gulp-starter-kit#5]
Привет. В сборке gulp-starter-kit в файле gulpfile.js необходимо заменить
babel({
        presets: ['env']
      })
на 
babel({
        presets: ['@babel/env']
      })

Пруф: https://www.npmjs.com/package/gulp-babel раздел Usage.
Без этого сборка выдает ошибки.

И так же в том же файле gulpfile.js 
В задачу 'watch' строчку gulp.watch('src/js/**/*.js', ['scripts']); заменить на 
gulp.watch('src/js/**/*.js', ['scripts']).on('change', browserSync.reload);
 Чтоб браузер перезагружал страницу после изменений js файлов. Без этого неудобно работать с файлами js.

**Comment by luxplanjay** [comment]
Привет, точно, пакеты обновил и забыл обновить, там ещё бабелрс надо
поправить если есть.

Я только в понедельник доберусь, сделай пул реквест с правками если есть
время, приеду солью сразу)
